### ISSUE TITLE
 Failed building wheel for pynvx

### ISSUE THREAD

**Issue by PeterZerg** [1132719438/pynvx#4]
WL-197-198:faceswap-master zerg$ pip install ./pynvx
Processing ./pynvx
Building wheels for collected packages: pynvx
  Building wheel for pynvx (setup.py) ... error
  Complete output from command /Applications/anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/nj/f8_k8ccn0v58by9sqzj9jnx00000gp/T/pip-req-build-7soq5bmp/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/nj/f8_k8ccn0v58by9sqzj9jnx00000gp/T/pip-wheel-c6ojwdza --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.7-x86_64-3.6
  creating build/lib.macosx-10.7-x86_64-3.6/pynvx
  copying pynvx/pynvml.py -> build/lib.macosx-10.7-x86_64-3.6/pynvx
  copying pynvx/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/pynvx
  running build_ext
  -- The C compiler identification is AppleClang 10.0.1.10010046
  -- The CXX compiler identification is AppleClang 10.0.1.10010046
  -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
  -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
  -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found PythonInterp: /Applications/anaconda/bin/python (found version "3.6.1")
  -- Found PythonLibs: /Applications/anaconda/lib/libpython3.6m.dylib
  -- Performing Test HAS_CPP14_FLAG
  -- Performing Test HAS_CPP14_FLAG - Success
  -- pybind11 v2.3.dev0
  -- Performing Test HAS_FLTO
  -- Performing Test HAS_FLTO - Success
  -- LTO enabled
  CMake Error at /Applications/anaconda/lib/python3.6/site-packages/cmake/data/CMake.app/Contents/share/cmake-3.13/Modules/FindCUDA.cmake:696 (message):
    Specify CUDA_TOOLKIT_ROOT_DIR
  Call Stack (most recent call first):
    CMakeLists.txt:8 (find_package)
  
  
  -- Configuring incomplete, errors occurred!
  See also "/private/var/folders/nj/f8_k8ccn0v58by9sqzj9jnx00000gp/T/pip-req-build-7soq5bmp/build/temp.macosx-10.7-x86_64-3.6/CMakeFiles/CMakeOutput.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/nj/f8_k8ccn0v58by9sqzj9jnx00000gp/T/pip-req-build-7soq5bmp/setup.py", line 103, in <module>
      "Topic :: Software Development :: Libraries :: Python Modules",
    File "/Applications/anaconda/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/Applications/anaconda/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/Applications/anaconda/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/Applications/anaconda/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/Applications/anaconda/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "/Applications/anaconda/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Applications/anaconda/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/Applications/anaconda/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/Applications/anaconda/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Applications/anaconda/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/private/var/folders/nj/f8_k8ccn0v58by9sqzj9jnx00000gp/T/pip-req-build-7soq5bmp/setup.py", line 32, in run
      self.build_extension(ext)
    File "/private/var/folders/nj/f8_k8ccn0v58by9sqzj9jnx00000gp/T/pip-req-build-7soq5bmp/setup.py", line 56, in build_extension
      subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
    File "/Applications/anaconda/lib/python3.6/subprocess.py", line 291, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '/private/var/folders/nj/f8_k8ccn0v58by9sqzj9jnx00000gp/T/pip-req-build-7soq5bmp', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/private/var/folders/nj/f8_k8ccn0v58by9sqzj9jnx00000gp/T/pip-req-build-7soq5bmp/build/lib.macosx-10.7-x86_64-3.6', '-DPYTHON_EXECUTABLE=/Applications/anaconda/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
  
  ----------------------------------------
  Failed building wheel for pynvx
  Running setup.py clean for pynvx
Failed to build pynvx
Installing collected packages: pynvx
  Found existing installation: pynvx 1.0.0
    Uninstalling pynvx-1.0.0:
      Successfully uninstalled pynvx-1.0.0
  Running setup.py install for pynvx ... error
    Complete output from command /Applications/anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/nj/f8_k8ccn0v58by9sqzj9jnx00000gp/T/pip-req-build-7soq5bmp/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/nj/f8_k8ccn0v58by9sqzj9jnx00000gp/T/pip-record-e3wtxc74/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.7-x86_64-3.6
    creating build/lib.macosx-10.7-x86_64-3.6/pynvx
    copying pynvx/pynvml.py -> build/lib.macosx-10.7-x86_64-3.6/pynvx
    copying pynvx/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/pynvx
    running build_ext
    -- The C compiler identification is AppleClang 10.0.1.10010046
    -- The CXX compiler identification is AppleClang 10.0.1.10010046
    -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
    -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
    -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Found PythonInterp: /Applications/anaconda/bin/python (found version "3.6.1")
    -- Found PythonLibs: /Applications/anaconda/lib/libpython3.6m.dylib
    -- Performing Test HAS_CPP14_FLAG
    -- Performing Test HAS_CPP14_FLAG - Success
    -- pybind11 v2.3.dev0
    -- Performing Test HAS_FLTO
    -- Performing Test HAS_FLTO - Success
    -- LTO enabled
    CMake Error at /Applications/anaconda/lib/python3.6/site-packages/cmake/data/CMake.app/Contents/share/cmake-3.13/Modules/FindCUDA.cmake:696 (message):
      Specify CUDA_TOOLKIT_ROOT_DIR
    Call Stack (most recent call first):
      CMakeLists.txt:8 (find_package)
    
    
    -- Configuring incomplete, errors occurred!
    See also "/private/var/folders/nj/f8_k8ccn0v58by9sqzj9jnx00000gp/T/pip-req-build-7soq5bmp/build/temp.macosx-10.7-x86_64-3.6/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/nj/f8_k8ccn0v58by9sqzj9jnx00000gp/T/pip-req-build-7soq5bmp/setup.py", line 103, in <module>
        "Topic :: Software Development :: Libraries :: Python Modules",
      File "/Applications/anaconda/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/Applications/anaconda/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Applications/anaconda/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/Applications/anaconda/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Applications/anaconda/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/Applications/anaconda/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/Applications/anaconda/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Applications/anaconda/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Applications/anaconda/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/Applications/anaconda/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Applications/anaconda/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/private/var/folders/nj/f8_k8ccn0v58by9sqzj9jnx00000gp/T/pip-req-build-7soq5bmp/setup.py", line 32, in run
        self.build_extension(ext)
      File "/private/var/folders/nj/f8_k8ccn0v58by9sqzj9jnx00000gp/T/pip-req-build-7soq5bmp/setup.py", line 56, in build_extension
        subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
      File "/Applications/anaconda/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/private/var/folders/nj/f8_k8ccn0v58by9sqzj9jnx00000gp/T/pip-req-build-7soq5bmp', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/private/var/folders/nj/f8_k8ccn0v58by9sqzj9jnx00000gp/T/pip-req-build-7soq5bmp/build/lib.macosx-10.7-x86_64-3.6', '-DPYTHON_EXECUTABLE=/Applications/anaconda/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
    
    ----------------------------------------
  Rolling back uninstall of pynvx
  Moving to /Applications/anaconda/lib/python3.6/site-packages/_pynvx.cpython-36m-darwin.so
   from /private/var/folders/nj/f8_k8ccn0v58by9sqzj9jnx00000gp/T/pip-uninstall-6d3ambtd/_pynvx.cpython-36m-darwin.so
  Moving to /Applications/anaconda/lib/python3.6/site-packages/pynvx-1.0.0.dist-info/
   from /Applications/anaconda/lib/python3.6/site-packages/~ynvx-1.0.0.dist-info
  Moving to /Applications/anaconda/lib/python3.6/site-packages/pynvx/
   from /Applications/anaconda/lib/python3.6/site-packages/~ynvx
Command "/Applications/anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/nj/f8_k8ccn0v58by9sqzj9jnx00000gp/T/pip-req-build-7soq5bmp/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/nj/f8_k8ccn0v58by9sqzj9jnx00000gp/T/pip-record-e3wtxc74/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/nj/f8_k8ccn0v58by9sqzj9jnx00000gp/T/pip-req-build-7soq5bmp/

**Comment by PeterZerg** [comment]
The errors are:

1. Failed building wheel for pynvx

2. Command "/Applications/anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/nj/f8_k8ccn0v58by9sqzj9jnx00000gp/T/pip-req-build-7soq5bmp/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/nj/f8_k8ccn0v58by9sqzj9jnx00000gp/T/pip-record-e3wtxc74/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/nj/f8_k8ccn0v58by9sqzj9jnx00000gp/T/pip-req-build-7soq5bmp/

I tried to use different sources but still getting the same problem

**Comment by 1132719438** [comment]
You should install CUDA and set the environments [https://github.com/1132719438/pynvx/blob/master/TROUBLESHOOTING.md]()
