### ISSUE TITLE
Produce a wheel for python 3.8

### ISSUE THREAD

**Issue by MGough** [1132719438/pynvx#5]
There is no wheel for python 3.8 which makes installing and running libraries which are dependent on `pynvx` difficult on MacOS due to the lack of an Nvidia GPU on Apple devices. Instead pip attempts to build `pynvx` which fails due to the lack of `nvidia-toolkit`.

Several people have faced this issue: https://stackoverflow.com/questions/61576609/problem-installing-fastai-on-macos-10-15

**Comment by 1132719438** [comment]
Added
