### ISSUE TITLE
Manylinux wheels

### ISSUE THREAD

**Issue by JMMarchant** [1132719438/pynvx#6]
There are no Linux-available wheels which means that, similar to #5, installing and running libraries that are dependent on `pynvx` on CI/CD servers or GitHub Actions fails as it is unable to simply install from pip but tries to build the wheel from scratch. This fails due to the lack of `CUDA_TOOLKIT` in these environments and is not easily solvable to setup for a dependency compilation.

If possible, can we get some `manylinux`-flavoured wheels to aid installation in these environments?

**Comment by 1132719438** [comment]
Yeah, manylinux2010 wheels added

**Comment by JMMarchant** [comment]
Thank you so much!
