### ISSUE TITLE
wheel for python3.10

### ISSUE THREAD

**Issue by torzdf** [1132719438/pynvx#7]
Hello

Owner of deepfakes/faceswap here. A long time ago you created this lib to help enable MacOS users with Nvidia GPUs to use faceswap.

I'm not sure there are many MacOS/Nvidia users these days, but I have recently updated to Python 3.10,  just pushing through CI, when I realized pynvx won't work with it.

I don't know if you still maintain this lib, or if it would even be worth it, but if you are, is there any chance you could put out a Python3.10 wheel?

If not, no worries. I will disable MacOS/Nvidia support in the meantime.

Thanks in advance.

**Comment by 1132719438** [comment]
I will build and test it soon

**Comment by torzdf** [comment]
Thanks dude. Hugely appreciated!
